config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, :only => [:index, :new, :create, :show]
  resources :tickets
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :artist, presence: true
  validates :description, presence: true
  validates :price_low, presence: true, numericality: true
  validates :price_high, presence: true, numericality: true
  validates :event_date, presence: true 
  validate :event_date_not_from_past, :event_prices
  has_many :tickets

  def event_date_not_from_past
    if event_date < Date.today
      errors.add('Data wydarzenia', 'nie może być z przeszłości')
    end
  end

  def event_prices
    if price_low > price_high
      errors.add('Cena wydarzenia', 'low nie może być wieksza od high')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :name, presence: true, length: { minimum: 6 }
  validates :email_address, presence: true
  validates :price, presence: true
  validate :ticket_price
  belongs_to :event
  belongs_to :user

  def ticket_price
    if price < event.price_low
      errors.add('Cena biletu', 'mnijesza od minimalnej ceny na to wydarzenie')
    end
    if price > event.price_high
      errors.add('Cena biletu', 'większa od maksymalnej ceny na to wydarzenie')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models
  has_many :tickets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  before_action :check_logged_in, :only => [:new, :create]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
        event_parmas = params.require(:event).permit(:artist, :description,
        :price_low, :price_high, :event_date)

        @event = Event.new(event_parmas)
         if @event.save
           flash[:komunikat] = 'Event został poprawnie stworzony.'
           redirect_to "/events/#{@event.id}"
         else
          render 'new'
         end
  end

  def show
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def check_logged_in
      authenticate_or_request_with_http_basic("Ads") do |username, password|
      username == "admin" && password == "admin"
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = current_user.tickets.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
    end

    def correct_user
     @ticket = current_user.tickets.find_by(id: params[:id])
     redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, url: url) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price_low %>
    <%= form.text_area :price_low %>
  </div>

  <div class="field">
    <%= form.label :price_high %>
    <%= form.text_field :price_high %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.text_field :event_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_new_ticket.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <%= form.hidden_field :event_id, value: ticket.event_id %>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/events/_tickets_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1> Wszystkie wydarzenia</h1>
<ul>
 <% for event in @events %>
 <li><%= link_to event.artist, event %></li>
 <% end %>
</ul>
 

<button type="button" class="btn btn-info"><%= link_to 'Nowe ogłoszenie', new_event_path %></button>
<div class="spinner-grow text-primary" role="status">
  <span class="sr-only">Loading...</span>
</div>
<div class="spinner-grow" role="status">
  <span class="sr-only">Loading...</span>
</div>

<br>
<button type="button" class="btn btn-lg btn-danger" data-toggle="popover" title="Popover title" data-content="Event is a .......">What is event?</button>

 <script>
$(function () {
  $('[data-toggle="popover"]').popover()
})

 </script>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render partial: 'form', locals: {event: @event, url: '/events'} %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Low price:</strong>
  <%= @event.price_low %>
</p>

<p>
  <strong>High price:</strong>
  <%= @event.price_high %>
</p>


<br>
<br>
<br>

<%= render "tickets_list", tickets: @event.tickets %>

<br>
<br>
<br>

<%= render "new_ticket", ticket: Ticket.new( :event_id=>@event.id)  %>

<%= link_to 'All', '/events' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
 Logged in as <strong><%= current_user.email %></strong>.
 <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
 <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
%>
<% else %>
 <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
 <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>
</p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tickets/_events_list.html.erb
<h1> Wszystkie wydarzenia</h1>
<ul>
 <% for event in events %>
   <li><%=event.id %> <%= link_to event.artist, event %></li>
 <% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>


  <%= render "events_list", events: Event.all %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>


  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
    <tr>
    <td><%= ticket.name %></td>
    <td><%= link_to 'Wyświetl', ticket %></td>
    <% if ticket.user == current_user %>
     <td><%= link_to 'Edytuj', edit_ticket_path(ticket) %></td>
     <td><%= link_to 'Usuń', ticket, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
    <% end %>
     </tr>
     <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-info"><%= link_to 'New Ticket', new_ticket_path %></button>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Event id:</strong>
  <%= @ticket.event_id %>
</p>

<p>
  <strong>User id:</strong>
  <%= @ticket.user_id %>
</p>

<% if @ticket.user == current_user %>
<%= link_to 'Edycja', edit_ticket_path(@ticket) %>
<% end %>
 <%= link_to 'Wstecz', tickets_path %>